-- Tabela: Company
CREATE TABLE FD_T_COMPANY (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    cnpj VARCHAR2(20) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela: User
CREATE TABLE FD_T_APPUSER (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    profile VARCHAR2(20) CHECK (profile IN ('ADMIN', 'USER')) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    company_id NUMBER NOT NULL,
    CONSTRAINT fk_user_company FOREIGN KEY (company_id)
        REFERENCES FD_T_COMPANY(id) ON DELETE CASCADE
);

-- Tabela: BankAccount
CREATE TABLE FD_T_BANKACCOUNT (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    type VARCHAR2(20) CHECK (type IN ('CHECKING', 'SAVINGS', 'CASH', 'INVESTMENT')) NOT NULL,
    bank_name VARCHAR2(100),
    initial_balance NUMBER(15,2) DEFAULT 0 NOT NULL,
    company_id NUMBER NOT NULL,
    CONSTRAINT fk_bankaccount_company FOREIGN KEY (company_id)
        REFERENCES FD_T_COMPANY(id) ON DELETE CASCADE
);

-- Tabela: Category
CREATE TABLE FD_T_CATEGORY (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    type VARCHAR2(20) CHECK (type IN ('INCOME', 'EXPENSE')) NOT NULL,
    company_id NUMBER NOT NULL,
    parent_category_id NUMBER,
    CONSTRAINT fk_category_company FOREIGN KEY (company_id)
        REFERENCES FD_T_COMPANY(id) ON DELETE CASCADE,
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id)
        REFERENCES FD_T_CATEGORY(id) ON DELETE SET NULL
);

-- Tabela: Transactions
CREATE TABLE FD_T_TRANSACTIONS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(500) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    due_date DATE NOT NULL,
    payment_date DATE,
    transaction_type VARCHAR2(20) CHECK (transaction_type IN ('INCOME', 'EXPENSE', 'TRANSFER')) NOT NULL,
    transaction_status VARCHAR2(20) DEFAULT 'PENDING' CHECK (transaction_status IN ('PENDING', 'PAID', 'CANCELED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    bank_account_id NUMBER NOT NULL,
    category_id NUMBER,
    company_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_transaction_account FOREIGN KEY (bank_account_id)
        REFERENCES FD_T_BANKACCOUNT(id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_category FOREIGN KEY (category_id)
        REFERENCES FD_T_CATEGORY(id) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_company FOREIGN KEY (company_id)
        REFERENCES FD_T_COMPANY(id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_user FOREIGN KEY (user_id)
        REFERENCES FD_T_APPUSER(id) ON DELETE CASCADE
);

-- Tabela: Transfer
CREATE TABLE FD_T_TRANSFER (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMBER(15,2) NOT NULL,
    transfer_date DATE NOT NULL,
    description VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    origin_account_id NUMBER NOT NULL,
    destination_account_id NUMBER NOT NULL,
    company_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_transfer_origin FOREIGN KEY (origin_account_id)
        REFERENCES FD_T_BANKACCOUNT(id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_destination FOREIGN KEY (destination_account_id)
        REFERENCES FD_T_BANKACCOUNT(id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_company FOREIGN KEY (company_id)
        REFERENCES FD_T_COMPANY(id) ON DELETE CASCADE,
    CONSTRAINT fk_transfer_user FOREIGN KEY (user_id)
        REFERENCES FD_T_APPUSER(id) ON DELETE CASCADE
);

-- Índices opcionais para performance
CREATE INDEX idx_transaction_due_date ON FD_T_TRANSACTIONS(due_date);
CREATE INDEX idx_transaction_type ON FD_T_TRANSACTIONS(transaction_type);
CREATE INDEX idx_transfer_date ON FD_T_TRANSFER(transfer_date);